## name Basic passes.
## filename OK.pm
## failures 0
## cut

package Filename::OK;
1;

#------------------------------------------------------------------------------

## name Basic passes.
## filename Filename/OK.pm
## failures 0
## cut

package Filename::OK;
1;

#------------------------------------------------------------------------------

## name Basic passes.
## filename lib/Filename/OK.pm
## failures 0
## cut

package Filename::OK;
1;

#------------------------------------------------------------------------------

## name Basic passes.
## filename blib/lib/Filename/OK.pm
## failures 0
## cut

package Filename::OK;
1;

#------------------------------------------------------------------------------

## name Basic passes.
## filename OK.pl
## failures 0
## cut

package Filename::OK;
1;

#------------------------------------------------------------------------------

## name Basic passes.
## filename Filename-OK-1.00/OK.pm
## failures 0
## cut

package Filename::OK;
1;

#------------------------------------------------------------------------------

## name Basic passes.
## filename Filename-OK/OK.pm
## failures 0
## cut

package Filename::OK;
1;

#------------------------------------------------------------------------------

## name Basic passes.
## filename Foobar-1.00/OK.pm
## failures 0
## cut

package Filename::OK;
1;

#------------------------------------------------------------------------------

## name Basic Failure.
## filename Bad.pm
## failures 1
## cut

package Filename::OK;
1;

#------------------------------------------------------------------------------

## name Basic Failure.
## filename Filename/Bad.pm
## failures 1
## cut

package Filename::OK;
1;

#------------------------------------------------------------------------------

## name Basic Failure.
## filename lib/Filename/BadOK.pm
## failures 1
## cut

package Filename::OK;
1;

#------------------------------------------------------------------------------

## name Basic Failure.
## filename ok.pm
## failures 1
## cut

package Filename::OK;
1;

#------------------------------------------------------------------------------

## name Basic Failure.
## filename filename/OK.pm
## failures 1
## cut

package Filename::OK;
1;

#------------------------------------------------------------------------------

## name Basic Failure.
## filename Foobar/OK.pm
## failures 1
## cut

package Filename::OK;
1;

#------------------------------------------------------------------------------

## name first package is main, with inner package
## filename some_script
## failures 0
## cut

package main;

Inner::frobulate( @ARGV );

package Inner;

sub frobulate{};

1;

#------------------------------------------------------------------------------

## name second package is main, with inner package
## filename some_script
## failures 1
## cut

package Inner;

sub frobulate{};

package main;

Inner::frobulate( @ARGV );

1;

#------------------------------------------------------------------------------

## name Pass with apostrophe.
## filename Oh.pm
## failures 0
## cut

package D'Oh;
1;

#------------------------------------------------------------------------------

## name Pass with apostrophe.
## filename D/Oh.pm
## failures 0
## cut

package D'Oh;
1;

#------------------------------------------------------------------------------

## name Failure with apostrophe.
## filename oh.pm
## failures 1
## cut

package D'Oh;
1;

#------------------------------------------------------------------------------

## name Failure with apostrophe.
## filename d/Oh.pm
## failures 1
## cut

package D'Oh;
1;

#-----------------------------------------------------------------------------

## name programs are exempt
## failures 0
## filename foo.plx
## cut
#!/usr/bin/perl
package Wibble;

#-----------------------------------------------------------------------------

## name using #line directive with double-quoted filename
## filename Foo.pm
## failures 0
## cut

#line 99 "Bar.pm"
package Bar;

#-----------------------------------------------------------------------------

## name using #line directive with bareword filename
## filename Foo.pm
## failures 0
## cut

#line 99 Bar.pm
package Bar;

#-----------------------------------------------------------------------------

## name #line directive appears after package declaration
## filename Foo.pm
## failures 1
## cut

package Bar;
#line 99 Bar.pm

#-----------------------------------------------------------------------------

## name multiple #line directives
## filename Foo.pm
## failures 1
## cut

#line 99 Bar.pm
#line 999 Baz.pm
package Bar;

#-----------------------------------------------------------------------------

## name #line directive with multi-part path
## filename Wrong.pm
## failures 0
## cut

#line 99 Foo/Bar/Baz.pm
package Foo::Bar::Baz;

#-----------------------------------------------------------------------------

## name #line directive with multi-part path in lib/ dir
## filename lib/Wrong.pm
## failures 0
## cut

#line 99 lib/Foo/Bar/Baz.pm
package Foo::Bar::Baz;

#-----------------------------------------------------------------------------

## name #line directive with partially matching multi-part path
## filename Wrong.pm
## failures 0
## cut

#line 99 Foo/Bar/Baz.pm
package Baz;

#-----------------------------------------------------------------------------

## name no package declaration at all
## filename Foo.pm
## failures 0
## cut

1;

#-----------------------------------------------------------------------------

## name #line directive with no package declaration at all
## filename Foo.pm
## failures 0
## cut

#line 1 Baz.pm
1;

#-----------------------------------------------------------------------------

##############################################################################
#      $URL$
#     $Date$
#   $Author$
# $Revision$
##############################################################################

# Local Variables:
#   mode: cperl
#   cperl-indent-level: 4
#   fill-column: 78
#   indent-tabs-mode: nil
#   c-indentation-style: bsd
# End:
# ex: set ts=8 sts=4 sw=4 tw=78 ft=perl expandtab shiftround :
