## name no code, no need for a one
## failures 0
## cut
=pod

=head1 NO CODE IN HERE

=cut

#-----------------------------------------------------------------------------

## name basic pass
## failures 0
## cut
1;

#-----------------------------------------------------------------------------

## name pass with __END__
## failures 0
## cut
1;
__END__

#-----------------------------------------------------------------------------

## name pass with __DATA__
## failures 0
## cut
1;
__DATA__

#-----------------------------------------------------------------------------

## name pass with comments at the end
## failures 0
## cut
1;
# The end

#-----------------------------------------------------------------------------

## name pass with comment on the same line
## failures 0
## cut
1; # final true value

#-----------------------------------------------------------------------------

## name pass with extra space
## failures 0
## cut
1  ;   #With extra space.

#-----------------------------------------------------------------------------

## name pass with more spacing
## failures 0
## cut
  1  ;   #With extra space.

#-----------------------------------------------------------------------------

## name pass with 1 on last line, but not last statement
## failures 0
## cut
$foo = 2; 1;   #On same line..

#-----------------------------------------------------------------------------

## name fails with 0
## failures 1
## cut
0;

#-----------------------------------------------------------------------------

## name fail with closing sub
## failures 1
## cut
1;
sub foo {}

#-----------------------------------------------------------------------------

## name fail with END block
## failures 1
## cut
1;
END {}

#-----------------------------------------------------------------------------

## name fail with a non-zero true value
## failures 1
## cut
'Larry';

#-----------------------------------------------------------------------------

## name programs are exempt
## failures 0
## parms
## cut
#!/usr/bin/perl
my $foo = 42;

#-----------------------------------------------------------------------------

## name DESTROY sub hides the 1; (RT #27364)
## failures 0
## cut

DESTROY { warn 'DEAD'; }

1;

#-----------------------------------------------------------------------------

## name PPI parsing problem saw this as not ending with 1 (GH #696)
## failures 0
## cut

package  UQ::Net::AddressSpace;
use  warnings;
use  strict;
sub  v4_block {  my ($self, $id) = @_;  return $self->_sub_hash(['id', $id, 'v4-block']);  }
1;

#-----------------------------------------------------------------------------

## name Second PPI parsing problem (GH #607)
## failures 0
## cut

package Fail;

use strict;
use warnings;

sub x64_flag {
    my $self = shift;
    return $self->{param}{perl_64b};
}

1;
#-----------------------------------------------------------------------------
# Local Variables:
#   mode: cperl
#   cperl-indent-level: 4
#   fill-column: 78
#   indent-tabs-mode: nil
#   c-indentation-style: bsd
# End:
# ex: set ts=8 sts=4 sw=4 tw=78 ft=perl expandtab shiftround :
