## name simple failure
## failures 1
## cut

sub foo {
    $x += return 3;
}


#-----------------------------------------------------------------------------
## name more complex failure
## failures 1
## cut

sub foo {
    if ( bar() ) {
        $x = 'blah blah' .
        return 1;
    }
    return;
}

#-----------------------------------------------------------------------------
## name logical AND exceptions
## failures 0
## cut

sub foo {
    /foo/ &&  return 'found foo';
    /bar/ and return 'found bar';
}

#-----------------------------------------------------------------------------
## name logical OR exceptions
## failures 0
## cut

sub foo {
    /foo/ || return 'cannot find foo';
    /bar/ or return 'cannot find bar';
}

#-----------------------------------------------------------------------------
## name Other operators are not exceptions
## failures 3
## cut

sub foo {
    /bar/ & return 'Cannot be a bitwise AND';
}

sub foo {
    /bar/ | return 'Cannot be a bitwise OR';
}

#-----------------------------------------------------------------------------
## name More non-failures
## failures 0
## cut

return;
return 1;
return foo();
# $x += return 5;
sub foo { return }

$x = $hash{return};

#-----------------------------------------------------------------------------
# Local Variables:
#   mode: cperl
#   cperl-indent-level: 4
#   fill-column: 78
#   indent-tabs-mode: nil
#   c-indentation-style: bsd
# End:
# ex: set ts=8 sts=4 sw=4 tw=78 ft=perl expandtab shiftround :
