## name sleep, as list
## failures 1
## cut

select( undef, undef, undef, 0.25 );

#-----------------------------------------------------------------------------

## name sleep, as list w/var
## failures 1
## cut

select( undef, undef, undef, $time );

#-----------------------------------------------------------------------------

## name sleep, as built-in
## failures 1
## cut

select undef, undef, undef, 0.25;

#-----------------------------------------------------------------------------

## name select on read
## failures 0
## cut

select $vec, undef, undef, 0.25;

#-----------------------------------------------------------------------------

## name select on write
## failures 0
## cut

select undef, $vec, undef, 0.25;

#-----------------------------------------------------------------------------

## name select on error
## failures 0
## cut

select undef, undef, $vec, 0.25;

#-----------------------------------------------------------------------------

## name select as word
## failures 0
## cut

$foo{select};

#-----------------------------------------------------------------------------

## name With three undefs, none of them the timeout. RT #37416
## failures 0
## cut

# Now block until the GUI passes the range back
    my $rin = '';
    my $rout = '';
    vec($rin, $parent->fileno(), 1) = 1;
    if (select($rout=$rin,undef,undef,undef)) {
     my $line;
     recv($parent, $line, 1000, 0);
     ($first, $last) = split ' ', $line;
    }

#-----------------------------------------------------------------------------

##############################################################################
#      $URL$
#     $Date$
#   $Author$
# $Revision$
##############################################################################

# Local Variables:
#   mode: cperl
#   cperl-indent-level: 4
#   fill-column: 78
#   indent-tabs-mode: nil
#   c-indentation-style: bsd
# End:
# ex: set ts=8 sts=4 sw=4 tw=78 ft=perl expandtab shiftround :
