## name Basic failure
## failures 4
## cut

$var = "";
$var = ''
$var = '     ';
$var = "     ";

#-----------------------------------------------------------------------------

## name Quote-like operator passing
## failures 0
## cut

$var = qq{};
$var = q{}
$var = qq{     };
$var = q{     };

#-----------------------------------------------------------------------------

## name Non-empty passing
## failures 0
## cut

$var = qq{this};
$var = q{that}
$var = qq{the};
$var = q{other};
$var = "this";
$var = 'that';
$var = 'the';
$var = "other";

#-----------------------------------------------------------------------------

## name Allow empty quotes succeeds
## failures 0
## parms {max_allowed_quoted_string_length => 0}
## cut

$var = q{};
$var = "";
$var = '';

#-----------------------------------------------------------------------------

## name Allow empty quotes failure
## failures 3
## parms {max_allowed_quoted_string_length => 0}
## cut

$var = q{ };
$var = " ";
$var = ' ';

#-----------------------------------------------------------------------------

## name Allow non-empty quotes succeeds
## failures 0
## parms {max_allowed_quoted_string_length => 2}
## cut

$var = q{};
$var = " ";
$var = '  ';

#-----------------------------------------------------------------------------

## name Allow non-empty quotes failure
## failures 3
## parms {max_allowed_quoted_string_length => 2}
## cut

$var = q{   };
$var = "   ";
$var = '   ';

#-----------------------------------------------------------------------------
# Local Variables:
#   mode: cperl
#   cperl-indent-level: 4
#   fill-column: 78
#   indent-tabs-mode: nil
#   c-indentation-style: bsd
# End:
# ex: set ts=8 sts=4 sw=4 tw=78 ft=perl expandtab shiftround :
